services:
  app:
    container_name: purwafest-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - postgres
    ports:
      - '8080:8080'
  postgres:
    container_name: purwafest-db
    image: 'postgres:17.2'
    env_file: .env
    ports:
      - '5433:5433'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
  redis:
    container_name: purwafest-redis
    image: 'redis:7.4'
    ports:
      - '6379:6379'

volumes:
  postgres_data: